# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-16 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20170804_1138'),
        ('email', '0002_auto_20170731_1707'),
    ]

    operations = [
    ]
