# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-24 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170731_1707'),
        ('core', '0010_auto_20170804_1138'),
    ]

    operations = [
    ]
