# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-24 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge'),
        ('core', '0010_auto_20170815_1414'),
    ]

    operations = [
    ]
