# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-23 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170804_1138'),
        ('manager', '0008_auto_20170731_1707'),
    ]

    operations = [
    ]
